apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: hf9rm3hb3-python 
  janus-idp.io/tekton: hf9rm3hb3-python
  backstage.io/kubernetes-id: hf9rm3hb3-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hf9rm3hb3-python
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml