apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: hf9rm3hb3-python
  janus-idp.io/tekton: hf9rm3hb3-python
  backstage.io/kubernetes-id: hf9rm3hb3-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hf9rm3hb3-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
