apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: hf9rm3hb3-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hf9rm3hb3-python 
  name: hf9rm3hb3-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: hf9rm3hb3-python 
